import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Darker_Grotesque } from "next/font/google";
import "./globals.css";
import Nav from "@/components/nav";

const inter = Inter({ subsets: ["latin"] });
const grotesque = Darker_Grotesque({subsets: ["latin"]})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={grotesque.className}>
        <div className="lg:mx-12 md:mx-8 mx-0">
          <Nav />
          {children}
        </div>
      </body>
    </html>
  );
}
